jobs:
- job: Build
  displayName: Build Maven Project
  steps:
  - task: Maven@3
    displayName: 'Maven Package'
    inputs:
      mavenPomFile: 'pom.xml'
# Copy files
# Copy the JAR package to the server where you want to deploy it.
  - task: CopyFiles@2
    inputs:
       SourceFolder: '$(System.DefaultWorkingDirectory)'
       TargetFolder: '/var/www/my-app'

- deployment: VMDeploy
  displayName: Web deploy
  environment:
    name:  ubuntu-dev
    resourceType: VirtualMachine
